Battle_Service/config/routes.rb
Rails.application.routes.draw do
  root :to =>"monsters#index"
  resources :monsters do
   collection { post :import}
   member do
    get 'fight'
    get 'escape'
   end
  end

end

Battle_Service/app/models/monster.rb
class Monster < ActiveRecord::Base
  require 'csv'
  self.primary_key = 'location'

  # CSV File Import Function
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
     Monster.create! row.to_hash
    end
  end

end

Battle_Service/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Battle_Service/app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :update, :destroy]
  respond_to :json, :html

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # Importation of Monster Data
  def import
   begin
    Monster.import(params[:file])
    redirect_to monsters_path, notice: "Monster Characters Data Loaded."
   rescue
    redirect_to monsters_path, notice: "Invalid CSV file format."
   end
  end
     
  def fight
  end
 
  def escape 
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:location, :name, :description, :strength)
    end
end

Battle_Service/app/helpers/application_helper.rb
module ApplicationHelper
end

Battle_Service/app/helpers/monsters_helper.rb
module MonstersHelper
end

Battle_Service/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EncounterService</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Battle_Service/app/views/monsters/_form.html.erb
<%= form_for(@monster) do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.number_field :location %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :strength %><br>
    <%= f.number_field :strength %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Battle_Service/app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

Battle_Service/app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Monsters</h1>

<h2>Import Monsters</h2>
<%= form_tag import_monsters_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Name</th>
      <th>Description</th>
      <th>Strength</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.location %></td>
        <td><%= monster.name %></td>
        <td><%= monster.description %></td>
        <td><%= monster.strength %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path %>

Battle_Service/app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form' %>

<%= link_to 'Back', monsters_path %>

Battle_Service/app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @monster.location %>
</p>

<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @monster.description %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @monster.strength %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>