Save_Service/config/routes.rb
Rails.application.routes.draw do

  resources :games

  resources :accounts

end

Save_Service/app/models/game.rb
class Game < ActiveRecord::Base
	self.primary_key = 'name'
end

Save_Service/app/models/users.rb
class Users < ActiveRecord::Base
end

Save_Service/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Save_Service/app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :set_game, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
   @game = Game.find(params[:id])
   render :template => "games/show"
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # added by Geoffe
    def to_param
      name
    end
 
    def self.find(s)
      self.find_by_name(s)
    end
    # end of Geoffe's code block

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :num_kills, :strength_level, :location_number)
    end
end

Save_Service/app/controllers/users_controller.rb
class UsersController < ApplicationController
	respond_to :json, :html
  
  def show
    @account = Account.find(params[:id])
    respond_with @account
  end
end

Save_Service/app/helpers/application_helper.rb
module ApplicationHelper
end

Save_Service/app/helpers/games_helper.rb
module GamesHelper
end

Save_Service/app/helpers/users_helper.rb
module UsersHelper
end

Save_Service/app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :num_kills %><br>
    <%= f.number_field :num_kills %>
  </div>
  <div class="field">
    <%= f.label :strength_level %><br>
    <%= f.number_field :strength_level %>
  </div>
  <div class="field">
    <%= f.label :location_number %><br>
    <%= f.number_field :location_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Save_Service/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

Save_Service/app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Num kills</th>
      <th>Strength level</th>
      <th>Location number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.num_kills %></td>
        <td><%= game.strength_level %></td>
        <td><%= game.location_number %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

Save_Service/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

Save_Service/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Num kills:</strong>
  <%= @game.num_kills %>
</p>

<p>
  <strong>Strength level:</strong>
  <%= @game.strength_level %>
</p>

<p>
  <strong>Location number:</strong>
  <%= @game.location_number %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

Save_Service/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaveService</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>